apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secure-nginx
  name: secure-nginx
spec:
  securityContext:
    runAsNonRoot: false
  containers:
  - image: nginx
    name: secure-nginx
    volumeMounts:
    - mountPath: /var/cache/nginx
      name: cache-volume
    - mountPath: /var/run
      name: run-volume
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
      privileged: false
      capabilities:
        drop: ["SYS_TIME", "NET_ADMIN"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 50Mi
  - name: run-volume
    emptyDir:
      sizeLimit: 50Mi
