apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  # das Target bezieht sich auf den CPU Request des gesamten Pods
  # es ist von daher ein MUSS die Ressourcen Requests zu setzen, damit das funktioniert
  targetCPUUtilizationPercentage: 25
