apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.25.0
        name: nginx
        resources:
          requests:
            memory: 5Mi
            cpu: 10m
          limits:
            memory: 5Mi # <-- increase to 50Mi if necessary
            # cpu: 100m # <-- anti-pattern limiting cpu
