---
apiVersion: v1
data:
  # secret key base64 encoded
  secret-access-key: CHANGEME # <--- adjust here CHANGEME
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
type: Opaque
