apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-apache
  name: php-apache
spec:
  replicas: 10
  selector:
    matchLabels:
      app: php-apache
  strategy:
    rollingUpdate:
      # wir möchten, bei einem Deployment, 100% aller Pods direkt neu erstellen
      maxSurge: 100%
      # wir möchten, bei einem Deployment, das maximal 50% aller Pods gleichzeitig down gehen
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      affinity:
        # Pod soll NICHT auf und der selben Node gescheduled werden
        podAntiAffinity:
          # aber wenn er schon mal drauf läuft, dann egal
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                # anhand folgender Pod Labels soll entschieden werden
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - php-apache
                # die Auswirkung soll auf die Node anhand ihres Namens erfolgen
                topologyKey: "kubernetes.io/hostname"
      containers:
      #- image: nginx
      - image: gcr.io/google_containers/hpa-example
        name: hpa-example
        resources:
          requests:
            memory: 64Mi
            cpu: 70m
          limits:
            memory: 64Mi
            cpu: 70m
        ports:
          - containerPort: 80
            name: http
        livenessProbe:
          exec:
            command:
            - cat
            - /var/www/html/index.php
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5