apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        # Pod should NOT be scheduled on the same NODE
        podAntiAffinity:
          # if it already runs on it we do not care
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                # decide upon these Pod labels
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - nginx
                # takes effect on a Node determined by its name
                topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx:1.25.0
        name: nginx
