---
helmDefaults:
  wait: true
  timeout: 1200

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  # external-dns
  - name: external-dns
    namespace: external-dns
    chart: bitnami/external-dns
    version: 6.19.1
    missingFileHandler: Warn
    values:
      - values-custom-external-dns.yaml

  # cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.11.1
    missingFileHandler: Warn
    set:
      - name: installCRDs
        value: true

  # ingress-nginx
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.6.0
    missingFileHandler: Warn
    values:
      - values-custom-ingress-nginx.yaml
    needs:
      - external-dns/external-dns
