apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-application
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
# If there was no wildcard certificate prepared yet, the following
# annotation and label would instruct cert-manager to create a certificate
# instantly.
#
#    cert-manager.io/cluster-issuer: letsencrypt-production
#  labels:
#    cert-manager.io/solver: dns01
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web-application-<YOURNAME>.workshop.metakube.org # <-- please adjust <YOURNAME>
      secretName: workshop-tls-cert
  rules:
    - host: web-application-<YOURNAME>.workshop.metakube.org # <-- please adjust <YOURNAME>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-application
                port:
                  number: 80
